### ISSUE TITLE
distance for crosslinks

### ISSUE THREAD

**Issue by Samuel-gwb** [Rappsilber-Laboratory/AlphaLink2#14]
Great work !  I have a question that what is the distance for a crosslinking input like following:
5 A 5 A 0.1
Will it be 25 Ang ? How to define the distance for such a crosslinking data due to different crosslinking reagent?

**Comment by grandrea** [comment]
hello, alphalink2 is currently trained with 25 angstrom data. So that line indicates a residue pair with 25 angstrom between residue 5 of chain A and residue 5 of chain A with a false discovery rate of 0.1 (10%). Currently, the distance cannot be changed, but it is not a distance restraint in the traditional sense- it is the maximum crosslinker distance used in training the network. 

Others have already used this with different crosslinkers, as AL2 weighs both experimental and MSA evidence, and indication of proximity is often enough to drive the prediction to the correct state.

disclaimer: I am not the AL2 developer, i was involved in developing AL1.

**Comment by grandrea** [comment]
I have been using AL2 for bs3 and dsso with ok results (the lower restraint density makes things harder). I also would say that 35 is not a generally agreed cutoff for bs3 CA-CA, groups work with anything between 22 to 35 depending how much backbone flexibility is thought to play a role...

I don't know about the parser specification for cutoff, though i know the cutoff in the colab is about plotting crosslinks on structures only.

**Comment by lhatsk** [comment]
The cutoff is just for the calculation of the crosslink satisfaction. It's by default 25 A because that's what the network was trained on. We also have another network which was trained on photoAA crosslinks (10 A).

**Comment by Samuel-gwb** [comment]
> The cutoff is just for the calculation of the crosslink satisfaction. It's by default 25 A because that's what the network was trained on. We also have another network which was trained on photoAA crosslinks (10 A).

Yes! I've checked with different cutoff, 25 A, 35 A, 45 A. The resulted structure is simillar while output satisfaction ratio gradually increases. 
Thanks!
